/**
 * Application constants
 */

export const MEMBER_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  SUSPENDED: 'suspended'
};

export const TRANSACTION_TYPE = {
  INCOME: 'income',
  EXPENSE: 'expense'
};

export const TRANSACTION_STATUS = {
  COMPLETED: 'completed',
  PENDING: 'pending',
  FAILED: 'failed'
};

export const EVENT_STATUS = {
  SCHEDULED: 'scheduled',
  ONGOING: 'ongoing',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled'
};

export const MESSAGE_STATUS = {
  DELIVERED: 'delivered',
  FAILED: 'failed',
  READ: 'read'
};

export const REPORT_STATUS = {
  COMPLETED: 'completed',
  PENDING: 'pending',
  FAILED: 'failed'
};

export const SERVICE_PORTS = {
  API_GATEWAY: 3001,
  MEMBER_SERVICE: 3002,
  ATTENDANCE_SERVICE: 3003,
  FINANCIAL_SERVICE: 3004,
  EVENT_SERVICE: 3005,
  COMMUNICATION_SERVICE: 3006,
  REPORTING_SERVICE: 3007
};

export const KPI_TARGETS = {
  REGISTRATION_SUCCESS_RATE: 0.99,
  REGISTRATION_TIME_MAX_MS: 2 * 60 * 1000,
  SEARCH_RESPONSE_TIME_MAX_MS: 2 * 1000,
  DUPLICATE_RECORD_RATE_MAX: 0.01,
  ATTENDANCE_ACCURACY: 0.98,
  ATTENDANCE_RECORDING_TIME_MAX_MS: 5 * 60 * 1000,
  MAX_ATTENDEES_PER_SERVICE: 500,
  ATTENDANCE_REPORT_GENERATION_TIME_MAX_MS: 3 * 1000,
  TRANSACTION_ACCURACY: 0.995,
  FINANCIAL_REPORT_GENERATION_TIME_MAX_MS: 5 * 1000,
  CALCULATION_ERROR_RATE_MAX: 0.005,
  EVENT_CREATION_TIME_MAX_MS: 2 * 60 * 1000,
  EVENT_UPDATE_SUCCESS_RATE: 0.99,
  MESSAGE_DELIVERY_RATE: 0.95,
  MESSAGE_SENDING_TIME_MAX_MS: 10 * 1000,
  BULK_NOTIFICATION_CAPACITY: 1000,
  REPORT_SUCCESS_RATE: 0.99,
  REPORTING_GENERATION_TIME_MAX_MS: 5 * 1000,
  REPORT_DATA_ACCURACY: 0.99,
  PAGE_LOAD_TIME_MAX_MS: 3 * 1000,
  SYSTEM_RESPONSE_TIME_MAX_MS: 2 * 1000,
  MIN_CONCURRENT_USERS: 50,
  SYSTEM_UPTIME_TARGET: 0.99,
  RECOVERY_TIME_MAX_MS: 1 * 60 * 60 * 1000,
  LEARNING_TIME_MAX_MINUTES: 30,
  USER_SATISFACTION_TARGET: 0.85,
  USER_ERROR_RATE_MAX: 0.05,
  MAX_SUPPORTED_MEMBERS: 10000,
  PERFORMANCE_DEGRADATION_MAX: 0.10,
  BUG_FIX_TIME_MAX_HOURS: 48,
  UPDATE_WITHOUT_DOWNTIME_RATE: 0.90,
  MOBILE_RESPONSIVENESS_MIN: 0.90
};

export default {
  MEMBER_STATUS,
  TRANSACTION_TYPE,
  TRANSACTION_STATUS,
  EVENT_STATUS,
  MESSAGE_STATUS,
  REPORT_STATUS,
  SERVICE_PORTS,
  KPI_TARGETS
};

